import test from 'node:test';
import assert from 'node:assert/strict';

import { qrModules, barcodeWidths, labelPayload, buildLabelPdf } from '../src/services/labels.js';

/* ============================================================================
   The QR encoder in services/labels.js is written by hand — bit stream,
   Reed-Solomon, module placement and masking. Nothing downstream would notice
   if it were subtly wrong: the label prints, it looks like a QR code, and the
   fault only surfaces when someone on the floor points a scanner at it and
   nothing happens.

   So this decodes it. The decoder below is written from the specification's
   reading order rather than from the encoder, and it is first proved against a
   matrix produced by an independent implementation (the Dart `qr` package,
   captured by frontend/tool/qr_reference.dart). A decoder that can read a
   known-good code, and then reads ours back to the same payload, is real
   evidence the labels scan.
   ========================================================================== */

/// A 25×25 QR for '90210-ABX|INV-77001|270' — the exact payload shape a label
/// carries — generated by the `qr` Dart package, which chose its own mask.
const REFERENCE_PAYLOAD = '90210-ABX|INV-77001|270';
const REFERENCE = [
  '1111111011010100101111111', '1000001001001000001000001', '1011101011100111101011101',
  '1011101000100100101011101', '1011101000101100101011101', '1000001010110000101000001',
  '1111111010101010101111111', '0000000000000011100000000', '1010001101001001000100101',
  '1100100101100111011100011', '0010001100101101000111011', '1101010000111001100010000',
  '0100011111001011001010011', '0100000000101011000100011', '1100011110001011010100111',
  '0011000101011000110000010', '1101111010000010111110010', '0000000010000010100010011',
  '1111111010110000101011111', '1000001000100010100010011', '1011101001111011111111001',
  '1011101001101010110001110', '1011101011001110111010111', '1000001001011001011101000',
  '1111111011001110110111101',
].map((row) => [...row].map((ch) => ch === '1'));

/* ---- an independent decoder, written from the spec ------------------- */

const MASKS = [
  (i, j) => (i + j) % 2 === 0,
  (i, j) => i % 2 === 0,
  (i, j) => j % 3 === 0,
  (i, j) => (i + j) % 3 === 0,
  (i, j) => (Math.floor(i / 2) + Math.floor(j / 3)) % 2 === 0,
  (i, j) => ((i * j) % 2) + ((i * j) % 3) === 0,
  (i, j) => ((((i * j) % 2) + ((i * j) % 3)) % 2) === 0,
  (i, j) => ((((i + j) % 2) + ((i * j) % 3)) % 2) === 0,
];

/** Version 2 has no version-information block; these are its function patterns. */
function isFunctionModule(n, r, c) {
  if (r <= 8 && c <= 8) return true;                       // top-left finder + format
  if (r <= 8 && c >= n - 8) return true;                   // top-right finder + format
  if (r >= n - 8 && c <= 8) return true;                   // bottom-left finder + format
  if (r === 6 || c === 6) return true;                     // timing
  if (r >= 16 && r <= 20 && c >= 16 && c <= 20) return true; // alignment at (18,18)
  return false;
}

/** The 15 format bits, read from the copy around the top-left finder. */
function readFormat(m) {
  const bits = [];
  for (let i = 0; i <= 5; i++) bits.push(m[8][i] ? 1 : 0);
  bits.push(m[8][7] ? 1 : 0);
  bits.push(m[8][8] ? 1 : 0);
  bits.push(m[7][8] ? 1 : 0);
  for (let i = 5; i >= 0; i--) bits.push(m[i][8] ? 1 : 0);
  const raw = parseInt(bits.join(''), 2) ^ 0b101010000010010;
  return { ec: (raw >> 13) & 0b11, mask: (raw >> 10) & 0b111 };
}

function decode(m) {
  const n = m.length;
  const { mask } = readFormat(m);
  const isMasked = MASKS[mask];

  const bits = [];
  let upward = true;
  for (let col = n - 1; col > 0; col -= 2) {
    if (col === 6) col--;                                  // skip the timing column
    for (let i = 0; i < n; i++) {
      const row = upward ? n - 1 - i : i;
      for (let k = 0; k < 2; k++) {
        const cc = col - k;
        if (isFunctionModule(n, row, cc)) continue;
        let bit = m[row][cc] ? 1 : 0;
        if (isMasked(row, cc)) bit ^= 1;
        bits.push(bit);
      }
    }
    upward = !upward;
  }

  const mode = parseInt(bits.slice(0, 4).join(''), 2);
  assert.equal(mode, 0b0100, 'expected byte mode');
  const len = parseInt(bits.slice(4, 12).join(''), 2);
  const bytes = [];
  for (let i = 0; i < len; i++) {
    bytes.push(parseInt(bits.slice(12 + i * 8, 20 + i * 8).join(''), 2));
  }
  return Buffer.from(bytes).toString('utf8');
}

/* ---- the decoder is only worth trusting once it reads a known-good code --- */

test('the decoder reads a QR produced by an independent implementation', () => {
  assert.equal(decode(REFERENCE), REFERENCE_PAYLOAD);
});

test('our encoder produces a code that decodes back to its payload', () => {
  for (const payload of [
    REFERENCE_PAYLOAD,
    '90211-ABX|INV-77001|340',
    'EV301-BMS|INV-77004|100',
    'A|B|1',
  ]) {
    const m = qrModules(payload).map((row) => row.map((v) => v === 1));
    assert.equal(decode(m), payload, `round trip failed for ${payload}`);
  }
});

test('the code carries the structure a scanner locks onto', () => {
  const m = qrModules(REFERENCE_PAYLOAD);
  assert.equal(m.length, 25, 'version 2 is 25 modules square');
  assert.ok(m.every((r) => r.length === 25));

  // three finder patterns: a 7×7 ring with a 3×3 core
  for (const [r0, c0] of [[0, 0], [0, 18], [18, 0]]) {
    for (let r = 0; r < 7; r++) {
      for (let c = 0; c < 7; c++) {
        const onRing = r === 0 || r === 6 || c === 0 || c === 6;
        const inCore = r >= 2 && r <= 4 && c >= 2 && c <= 4;
        assert.equal(m[r0 + r][c0 + c], onRing || inCore ? 1 : 0,
          `finder at ${r0},${c0} wrong at ${r},${c}`);
      }
    }
  }

  // timing patterns alternate
  for (let i = 8; i < 17; i++) {
    assert.equal(m[6][i], i % 2 === 0 ? 1 : 0, `horizontal timing at ${i}`);
    assert.equal(m[i][6], i % 2 === 0 ? 1 : 0, `vertical timing at ${i}`);
  }

  // the dark module is always set
  assert.equal(m[25 - 8][8], 1);

  // format info declares error-correction level M with mask 0
  const fmt = readFormat(m.map((r) => r.map((v) => v === 1)));
  assert.equal(fmt.ec, 0b00, 'EC level M');
  assert.equal(fmt.mask, 0, 'mask 0');
});

test('a payload longer than version 2 holds is truncated, not corrupted', () => {
  const long = 'X'.repeat(200);
  const m = qrModules(long).map((row) => row.map((v) => v === 1));
  const out = decode(m);
  assert.ok(out.length > 0 && long.startsWith(out), 'decodes to a prefix of the input');
  assert.ok(out.length <= 26, 'fits version 2 byte capacity');
});

/* ---- Code 128 ---------------------------------------------------------- */

test('the barcode is a well-formed Code 128-B symbol', () => {
  for (const part of ['90210-ABX', 'EV301-BMS', 'A']) {
    const w = barcodeWidths(part);

    // every symbol is 6 elements of 11 modules; the stop is 7 elements of 13
    assert.equal((w.length - 7) % 6, 0, `${part}: element count`);
    const symbols = (w.length - 7) / 6;
    assert.equal(symbols, part.length + 2, `${part}: start + data + check`);

    for (const v of w) assert.ok(v >= 1 && v <= 4, `${part}: element width ${v} out of range`);

    for (let s = 0; s < symbols; s++) {
      const sum = w.slice(s * 6, s * 6 + 6).reduce((a, b) => a + b, 0);
      assert.equal(sum, 11, `${part}: symbol ${s} is not 11 modules`);
    }
    assert.equal(w.slice(-7).reduce((a, b) => a + b, 0), 13, `${part}: stop pattern`);
  }
});

/* ---- payload + PDF ----------------------------------------------------- */

test('the label payload is the one string both the printer and the scanner use', () => {
  assert.equal(
    labelPayload({ part_no: '90210-ABX', invoice_no: 'INV-77001', grn_qty: 270 }),
    '90210-ABX|INV-77001|270',
  );
});

test('the label sheet is a PDF with one page per line', async () => {
  const lines = [1, 2, 3].map((i) => ({
    part_no: `PART-${i}`, part_desc: 'Description', invoice_no: `INV-${i}`,
    grn_qty: 100 * i, uom: 'NOS', vendor: 'Vendor', grn_date: '2026-09-09',
  }));
  const pdf = await buildLabelPdf(lines);
  assert.equal(pdf.subarray(0, 4).toString(), '%PDF');
  const pages = (pdf.toString('latin1').match(/\/Type \/Page[^s]/g) || []).length;
  assert.equal(pages, 3, 'one page per label');
});
